"""Reusable editorial purposes. These are principles, not observed performance claims."""

from ...domain.studios.contextual_editing import EditingTechniqueV1


def editorial_principles():
    definitions = [
        (
            "reaction_pause",
            "montage",
            "Pausa para reação",
            "Dar tempo para interpretar uma reação ou consequência.",
            "Entrevista e apresentação com reação relevante",
            "A pausa quebra uma frase ou sugere uma reação fora de contexto",
            "Trecho de reação com contexto e tempo de origem",
            ["cut"],
            {"hold": "Duração da reação, preservando a frase"},
        ),
        (
            "action_continuity",
            "montage",
            "Continuidade da ação",
            "Ligar planos da mesma ação sem perder sua direção.",
            "Demonstração com múltiplos ângulos",
            "Ângulos mostram ações ou momentos diferentes",
            "Planos correspondentes e intervalos identificados",
            ["cut"],
            {"cutPoint": "Momento da ação em cada fonte"},
        ),
        (
            "show_then_explain",
            "montage",
            "Resultado seguido de explicação",
            "Apresentar um resultado e depois demonstrar seu processo.",
            "Tutorial com resultado real registrado",
            "O resultado depende de uma ressalva que a nova ordem esconderia",
            "Resultado, processo e relação factual revisada",
            ["cut", "multitrack"],
            {"order": "Ordem explicitamente revisada"},
        ),
        (
            "comparison_views",
            "composition",
            "Comparação simultânea",
            "Permitir observar diferenças entre materiais correspondentes.",
            "Duas versões, produtos ou estados comparáveis",
            "Escala ou iluminação sugere uma diferença inexistente",
            "Duas fontes identificadas e comparáveis",
            ["multitrack", "reframe"],
            {"layout": "Posições, escala e espaço para rótulos"},
        ),
        (
            "screen_detail",
            "composition",
            "Detalhe de interface",
            "Ampliar a área da tela que explica a ação.",
            "Tutorial, jogo ou demonstração de aplicativo",
            "O recorte esconde o contexto ou reduz a resolução útil",
            "Captura da interface e região de interesse",
            ["reframe", "keyframes"],
            {"region": "Área de interesse", "motion": "Deslocamento e escala"},
        ),
        (
            "photo_movement",
            "composition",
            "Movimento sobre fotografia",
            "Conduzir o olhar numa imagem estática.",
            "Arquivo e fotografias com resolução suficiente",
            "Movimento cria impressão de ação não registrada",
            "Imagem com margem para recorte",
            ["multitrack", "keyframes"],
            {"scale": "Escala inicial/final", "position": "Destino do olhar"},
        ),
        (
            "speaker_label",
            "composition",
            "Identificação de participante",
            "Informar quem fala sem competir com a fala.",
            "Entrevista ou apresentação com identificação fornecida",
            "Nome, cargo ou vínculo não foi confirmado",
            "Identificação literal aprovada",
            ["text"],
            {"duration": "Tempo de leitura", "safeArea": "Margem do formato de destino"},
        ),
        (
            "archive_context",
            "montage",
            "Contextualização do arquivo",
            "Relacionar o material de arquivo ao relato e à sua origem.",
            "Narrativa histórica ou contextual",
            "Imagem de outra data ou lugar parece registro direto do fato",
            "Origem, data quando conhecida e relação com o roteiro",
            ["multitrack", "text"],
            {"label": "Contexto fornecido, sem datas inventadas"},
        ),
        (
            "dialogue_priority",
            "sound",
            "Fala em primeiro plano",
            "Manter a compreensão da fala sobre os demais sons.",
            "Diálogo com música ou ambiente",
            "Redução extrema faz a música oscilar de forma distrativa",
            "Trilhas separadas com papel sonoro identificado",
            ["audio_mix", "ducking"],
            {"gain": "Ganho relativo", "fades": "Entrada e saída suaves"},
        ),
        (
            "room_tone_bridge",
            "sound",
            "Continuidade de ambiente",
            "Evitar saltos de ambiente entre trechos relacionados.",
            "Entrevista montada a partir de cortes",
            "Ambiente importado muda o local aparente da gravação",
            "Som ambiente compatível e condições de uso",
            ["audio_mix"],
            {"gain": "Nível discreto", "fades": "Sobreposição entre intervalos"},
        ),
        (
            "sonic_punctuation",
            "sound",
            "Pontuação sonora",
            "Marcar uma mudança ou ação que precisa de atenção.",
            "Ação visual ou mudança de etapa",
            "Efeito repetitivo compete com a mensagem",
            "Efeito apropriado, evento visual e posição temporal",
            ["audio_mix"],
            {"onset": "Sincronização com a ação", "gain": "Intensidade relativa"},
        ),
        (
            "intentional_silence",
            "sound",
            "Silêncio intencional",
            "Criar espaço de atenção sem acrescentar trilha desnecessária.",
            "Pausa, contemplação ou demonstração compreensível sem música",
            "O silêncio remove informação sonora necessária",
            "Entendimento do papel do áudio original",
            ["audio_mix"],
            {"interval": "Intervalo sem complemento sonoro"},
        ),
        (
            "music_phrase",
            "sound",
            "Montagem por frase musical",
            "Relacionar a duração visual à estrutura da música.",
            "Vídeo sem fala ou sequência musical",
            "A sincronia obriga cortes que impedem compreender a ação",
            "Música disponível e pontos musicais verificados",
            ["cut", "audio_mix"],
            {"cuePoints": "Pontos temporais observados, não presumidos"},
        ),
    ]
    return [
        EditingTechniqueV1(
            id=identifier,
            group=group,
            title=title,
            purpose=purpose,
            suitable_when=[suitable],
            avoid_when=[avoid],
            prerequisites=[material],
            parameters=parameters,
            required_capabilities=capabilities,
            evidence_type="principle",
            sources=[],
            examples=[],
        )
        for identifier, group, title, purpose, suitable, avoid, material, capabilities, parameters in definitions
    ]
