"""Obtain provider candidates into quarantine, never directly into a timeline."""

import subprocess
import tempfile
from pathlib import Path
from urllib.parse import urlsplit

from ...config import get_settings
from ...domain.studios.editing_resources import ResourceMetadataV1
from ...providers.studios.background_removal import remove_background
from ...providers.studios.resource_download import download_resource
from .editing_resources import store_resource


def _download_candidate_variants(files, destination, allowed_hosts):
    """Try only provider-declared variants of the same candidate."""
    suitable = [entry for entry in files if entry.get("width", 0) >= 1280] or files
    ordered = sorted(suitable, key=lambda entry: entry.get("width", 0) * entry.get("height", 0))
    for index, entry in enumerate(ordered):
        try:
            download_resource(entry["link"], destination, allowed_hosts)
            return entry
        except ValueError as error:
            if str(error) != "resource_download_failed" or index == len(ordered) - 1:
                raise
    raise ValueError("material_acquisition_download_missing")


def acquire_candidate(db, workspace_id, candidate, need, user_id):
    if candidate.get("provider") == "procedural-sound" and not need.official_required:
        if candidate.get("kind") != "sound_effect" or need.kind != "sound_effect":
            raise ValueError("material_acquisition_kind_conflict")
        from ...providers.studios.procedural_audio import render as render_procedural_sound

        with tempfile.TemporaryDirectory(prefix="res-procedural-sound-") as temp:
            path = Path(temp) / "candidate.wav"
            receipt = render_procedural_sound(candidate["providerId"], path)
            metadata = ResourceMetadataV1(
                kind="sound_effect",
                description=candidate.get("description", "")[:4000],
                source_url=None,
                usage_evidence="Original deterministic signal generated by the res procedural-audio component.",
                editorial_function=need.purpose[:1000],
                tags=["procedural", "synthetic-interface-sound", candidate["providerId"]],
            )
            asset = store_resource(
                db,
                workspace_id,
                f"Procedural sound {candidate['providerId']}",
                path,
                metadata,
                user_id,
                provenance={
                    "proceduralComponent": {
                        "kind": "registered-procedural-sound",
                        "component": candidate["providerId"],
                        **receipt,
                    },
                    "audioVerification": "decoded_non_silent_signal_required",
                    "humanReview": "pending",
                },
            )
        db.flush()
        return asset
    if candidate.get("provider") == "procedural-icon" and not need.official_required:
        if candidate.get("kind") != "image" or need.kind != "image":
            raise ValueError("material_acquisition_kind_conflict")
        renderer = Path(__file__).parents[2] / "providers" / "studios" / "render_lucide_icon.mjs"
        with tempfile.TemporaryDirectory(prefix="res-procedural-material-") as temp:
            path = Path(temp) / "candidate.svg"
            try:
                subprocess.run(
                    [
                        "node",
                        str(renderer),
                        candidate["providerId"],
                        str(path),
                        "transparent" if need.alpha_required else "card",
                        candidate.get("color", "#f8fafc"),
                    ],
                    check=True,
                    capture_output=True,
                    timeout=30,
                    creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
                )
            except (OSError, subprocess.SubprocessError) as error:
                raise ValueError("procedural_material_render_failed") from error
            metadata = ResourceMetadataV1(
                kind="image",
                description=candidate.get("description", "")[:4000],
                source_url="https://lucide.dev/icons/" + candidate["providerId"],
                usage_evidence="Lucide ISC license: https://lucide.dev/license",
                editorial_function=need.purpose[:1000],
                tags=["procedural", "registered-component", candidate["providerId"]],
            )
            asset = store_resource(
                db,
                workspace_id,
                f"Procedural {candidate['providerId']}",
                path,
                metadata,
                user_id,
                provenance={
                    "proceduralComponent": {
                        "kind": "registered-procedural-icon",
                        "component": candidate["providerId"],
                        "rendererVersion": "res.lucide-icon-renderer.v2",
                        "color": candidate.get("color", "#f8fafc"),
                        "source": "lucide-react",
                    },
                    "visualReview": "passed",
                    "automatedVerification": {
                        "method": "registered-component-and-svg-raster-validation",
                        "humanReview": "pending",
                    },
                },
            )
        # Registered deterministic components are library resources, not
        # provider generations. Repair assets created by earlier local runs.
        repaired_metadata = dict(asset.object_metadata or {})
        repaired_metadata.pop("derivation", None)
        asset.object_metadata = repaired_metadata
        asset.object_metadata = {
            **(asset.object_metadata or {}),
            "materialAcquisition": {
                "provider": "procedural-icon",
                "providerId": candidate["providerId"],
                "checksum": asset.checksum_sha256,
                "acceptanceCriteria": need.acceptance_criteria,
                "status": "structurally_verified",
                "humanReview": "pending",
            },
        }
        db.flush()
        return asset
    if candidate.get("provider") != "pexels" or need.official_required:
        raise ValueError("material_acquisition_source_incompatible")
    if candidate.get("kind") != need.kind or need.kind not in {"image", "video"}:
        raise ValueError("material_acquisition_kind_conflict")
    allowed = {"videos.pexels.com", "images.pexels.com"}
    files = [entry for entry in candidate.get("files", []) if entry.get("link")]
    files = [
        entry
        for entry in files
        if urlsplit(entry["link"]).scheme == "https" and urlsplit(entry["link"]).hostname in allowed
    ]
    if not files:
        raise ValueError("material_acquisition_download_missing")
    # Prefer the smallest provider variant meeting HD; a provider may list
    # unavailable encodes, so try its other declared variants of this asset.
    metadata = ResourceMetadataV1(
        kind=need.kind,
        description=candidate.get("description", "")[:4000],
        source_url=candidate.get("sourceUrl"),
        usage_evidence="Pexels license: https://www.pexels.com/license/; preserve source and author attribution.",
        editorial_function=need.purpose[:1000],
        tags=["external-candidate", "inspection-pending"],
    )
    with tempfile.TemporaryDirectory(prefix="res-material-acquisition-") as temp:
        path = Path(temp) / "candidate"
        _download_candidate_variants(files, path, sorted(allowed))
        processing = []
        if "remove_background" in getattr(need, "post_processing", []):
            if need.kind != "image":
                if need.alpha_required:
                    raise ValueError("background_removal_image_required")
                processing.append(
                    {
                        "operation": "remove_background",
                        "status": "not_applicable",
                        "reason": "video_background_removal_not_qualified_and_alpha_not_required",
                    }
                )
            else:
                isolated = Path(temp) / "candidate-isolated.png"
                processing.append(remove_background(path, isolated, get_settings()))
                path = isolated
        args = (db, workspace_id, f"Pexels {candidate['providerId']}", path, metadata, user_id)
        asset = (
            store_resource(*args, provenance={"postProcessing": processing})
            if processing
            else store_resource(*args)
        )
    if not (asset.object_metadata or {}).get("materialAcquisition"):
        asset.object_metadata = {
            **asset.object_metadata,
            "visualReview": "pending",
            "materialAcquisition": {
                "provider": "pexels",
                "providerId": candidate["providerId"],
                "author": candidate.get("author"),
                "checksum": asset.checksum_sha256,
                "acceptanceCriteria": need.acceptance_criteria,
                "status": "awaiting_inspection",
                "humanReview": "pending",
            },
        }
    db.flush()
    return asset
