import React from 'react';
import { Activity, Clock3, FileSearch, ShieldCheck } from 'lucide-react';
import { useGovernance } from '../context/GovernanceContext';

const formatDateTime = (value: string) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value));

export const AuditLogsView: React.FC = () => {
  const { auditLogs, loading } = useGovernance();
  return <div className="mx-auto w-full max-w-[1300px] space-y-5 p-5 md:p-7"><header className="border-b border-white/[0.06] pb-5"><div className="mb-2 flex items-center gap-2 text-[9px] uppercase tracking-[0.2em] text-[#7C7C7C]"><ShieldCheck className="h-3.5 w-3.5" /> Segurança e rastreabilidade</div><h1 className="text-[22px] font-semibold tracking-[-0.035em] text-white">Logs de auditoria</h1><p className="mt-1 text-[10px] text-[#7f888d]">Registro imutável das ações críticas realizadas no Workspace.</p></header><section className="overflow-hidden rounded-xl border border-white/[0.065] bg-[#111111]"><div className="flex items-center justify-between border-b border-white/[0.055] p-4"><div className="flex items-center gap-2 text-[10px] font-medium text-white"><Activity className="h-4 w-4 text-[#7C7C7C]" />Atividade recente</div><span className="text-[8px] text-[#636b6f]">{auditLogs.length} eventos</span></div>{loading && auditLogs.length === 0 ? <div className="p-8 text-[10px] text-[#71797d]">Carregando eventos…</div> : <div className="divide-y divide-white/[0.045]">{auditLogs.map((entry) => <div key={entry.id} className="grid gap-3 p-4 sm:grid-cols-[36px_180px_1fr_auto] sm:items-center"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white/[0.045] text-[#7C7C7C]"><FileSearch className="h-4 w-4" /></span><div><div className="text-[9px] font-medium text-white">{entry.actorName}</div><div className="mt-0.5 font-mono text-[7px] text-[#60686c]">{entry.action}</div></div><div><div className="text-[9px] text-[#a3aaad]">{entry.detail}</div><div className="mt-0.5 font-mono text-[7px] text-[#596166]">{entry.resource}</div></div><div className="flex items-center gap-1.5 text-[7px] text-[#636b6f]"><Clock3 className="h-3 w-3" />{formatDateTime(entry.createdAt)}</div></div>)}</div>}</section></div>;
};
