import React from 'react';
import { Check, Link2, Plus, RefreshCw, ShieldCheck, Star, Unplug, Users } from 'lucide-react';
import { CONNECTED_ACCOUNTS } from '../data/mockData';
import type { ConnectedAccount } from '../types';

const hydrate = (account: ConnectedAccount, index: number): ConnectedAccount => ({
  ...account, name: account.name || `${account.platform.charAt(0).toUpperCase()}${account.platform.slice(1)} Clicko`,
  company: account.company || 'Clicko Studio', lastSync: account.lastSync || `${index + 2} min atrás`,
  permissions: account.permissions || ['Publicar conteúdo', 'Ler métricas', 'Gerenciar comentários'],
  isDefault: index === 0,
});

export function ConnectedAccountsView() {
  const [accounts, setAccounts] = React.useState(() => CONNECTED_ACCOUNTS.map(hydrate));
  const [syncing, setSyncing] = React.useState<string>();
  const update = (id: string, values: Partial<ConnectedAccount>) => setAccounts((current) => current.map((account) => account.id === id ? { ...account, ...values } : account));
  const sync = (id: string) => { setSyncing(id); window.setTimeout(() => { update(id, { lastSync: 'agora' }); setSyncing(undefined); }, 800); };

  return <div className="mx-auto w-full max-w-[1480px] space-y-5 p-6 2xl:p-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[0.24em] text-[#8bd132]">Integrações sociais</p><h1 className="mt-2 text-2xl font-semibold text-white">Contas Conectadas</h1><p className="mt-1 text-sm text-[#8f999f]">Canais utilizados pelo calendário, análises, publicações e automações.</p></div><button onClick={() => setAccounts((current) => [...current, hydrate({ id: `acc-${Date.now()}`, platform: 'facebook', handle: '@nova.conta', connected: false, followers: '0', bestTime: 'A calcular', engagement: '—' }, current.length)])} className="flex items-center gap-2 rounded-lg bg-[#8bd132] px-4 py-2.5 text-[10px] font-bold text-[#14200e]"><Plus className="h-4 w-4" />Conectar nova conta</button></div>
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{accounts.map((account) => <article key={account.id} className="rounded-xl border border-white/[0.07] bg-[#182126] p-5"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl border border-white/[0.06] bg-black/25 text-[11px] font-bold uppercase text-[#8bd132]">{account.platform.slice(0, 2)}</span><div><div className="flex items-center gap-2"><h2 className="text-[11px] font-semibold text-white">{account.name}</h2>{account.isDefault && <Star className="h-3 w-3 fill-[#8bd132] text-[#8bd132]" />}</div><p className="mt-0.5 text-[9px] text-[#89949a]">{account.handle} · {account.company}</p></div></div><span className={`rounded-full px-2 py-1 text-[7px] ${account.connected ? 'bg-[#8bd132]/10 text-[#8bd132]' : 'bg-red-400/10 text-red-300'}`}>{account.connected ? 'Conectada' : 'Desconectada'}</span></div><div className="mt-4 grid grid-cols-3 gap-2 rounded-lg bg-black/20 p-3 text-center"><div><span className="block text-[7px] text-[#6f7b80]">Seguidores</span><strong className="mt-1 block text-[10px] text-white">{account.followers}</strong></div><div><span className="block text-[7px] text-[#6f7b80]">Engajamento</span><strong className="mt-1 block text-[10px] text-[#8bd132]">{account.engagement}</strong></div><div><span className="block text-[7px] text-[#6f7b80]">Sincronização</span><strong className="mt-1 block text-[9px] text-white">{account.lastSync}</strong></div></div><div className="mt-4"><div className="flex items-center gap-1.5 text-[8px] font-medium text-[#aab3b7]"><ShieldCheck className="h-3.5 w-3.5 text-[#8bd132]" />Permissões concedidas</div><div className="mt-2 flex flex-wrap gap-1">{account.permissions?.map((permission) => <span key={permission} className="rounded-full bg-white/[0.04] px-2 py-1 text-[7px] text-[#7f8a90]">{permission}</span>)}</div></div><div className="mt-4 flex flex-wrap gap-2 border-t border-white/[0.055] pt-3"><button onClick={() => sync(account.id)} className="flex items-center gap-1.5 rounded-lg border border-white/[0.06] px-2.5 py-2 text-[8px] text-[#9ba5aa] hover:text-white"><RefreshCw className={`h-3 w-3 ${syncing === account.id ? 'animate-spin' : ''}`} />Sincronizar</button><button onClick={() => update(account.id, { isDefault: true })} className="flex items-center gap-1.5 rounded-lg border border-white/[0.06] px-2.5 py-2 text-[8px] text-[#9ba5aa] hover:text-white"><Check className="h-3 w-3" />Padrão</button><button onClick={() => update(account.id, { connected: !account.connected })} className="ml-auto flex items-center gap-1.5 rounded-lg px-2.5 py-2 text-[8px] text-[#7f8a90] hover:bg-red-400/[0.06] hover:text-red-300">{account.connected ? <Unplug className="h-3 w-3" /> : <Link2 className="h-3 w-3" />}{account.connected ? 'Desconectar' : 'Reconectar'}</button></div></article>)}</section>
    <div className="flex items-center gap-3 rounded-xl border border-white/[0.07] bg-[#182126] p-4 text-[9px] text-[#89949a]"><Users className="h-4 w-4 text-[#8bd132]" /><span>{accounts.length} contas agrupadas em 1 empresa. Estrutura pronta para múltiplas empresas e ambientes de trabalho.</span></div>
  </div>;
}
