import React from 'react';
import { FileText, FolderArchive, Image, Search, Sparkles, Upload, Video } from 'lucide-react';
import { useOperations } from '../context/OperationsContext';

export function LibraryView() {
  const { assets, posts, campaigns, addAsset } = useOperations();
  const [query, setQuery] = React.useState('');
  const [filter, setFilter] = React.useState('all');
  const combined = [
    ...assets,
    ...posts.map((post) => ({ id: post.id, workspaceId: post.workspaceId, title: post.title, type: (post.videoUrl ? 'video' : post.imageUrl ? 'image' : 'content') as 'video' | 'image' | 'content', tags: [post.platform, post.format], campaignId: post.campaignId, contentId: post.id, url: post.imageUrl || post.videoUrl, createdAt: post.createdAt, updatedAt: post.createdAt })),
    ...campaigns.map((campaign) => ({ id: `lib-${campaign.id}`, workspaceId: campaign.workspaceId, title: campaign.name, type: 'campaign' as const, tags: ['strategy', campaign.status], campaignId: campaign.id, createdAt: campaign.createdAt, updatedAt: campaign.updatedAt })),
  ];
  const filtered = combined.filter((asset) => (filter === 'all' || asset.type === filter) && `${asset.title} ${asset.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const icon = (type: string) => type === 'video' ? Video : type === 'image' ? Image : type === 'campaign' ? Sparkles : FileText;
  return <div className="mx-auto w-full max-w-[1480px] space-y-5 p-6 2xl:p-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[0.24em] text-[#8bd132]">Memória pesquisável</p><h1 className="mt-2 text-2xl font-semibold text-white">Biblioteca</h1><p className="mt-1 text-sm text-[#8f999f]">Conteúdos, uploads, campanhas, versões, prompts e materiais em um só índice.</p></div><button onClick={() => addAsset({ title: 'Novo material enviado', type: 'upload', tags: ['upload'] })} className="flex items-center gap-2 rounded-lg bg-[#8bd132] px-4 py-2.5 text-[11px] font-bold text-[#14200e]"><Upload className="h-4 w-4" />Adicionar material</button></div><div className="flex flex-wrap gap-2"><label className="flex h-10 min-w-[260px] flex-1 items-center gap-2 rounded-lg border border-white/[0.07] bg-[#182126] px-3"><Search className="h-4 w-4 text-[#78848a]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por conteúdo, campanha, tag ou formato..." className="w-full bg-transparent text-[10px] text-white outline-none" /></label>{['all', 'content', 'image', 'video', 'campaign', 'template', 'document'].map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-lg px-3 text-[9px] capitalize ${filter === item ? 'bg-[#8bd132] font-bold text-[#14200e]' : 'border border-white/[0.07] bg-[#182126] text-[#9ba5aa]'}`}>{item === 'all' ? 'Todos' : item}</button>)}</div><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">{filtered.map((asset) => { const Icon = icon(asset.type); return <article key={asset.id} className="group overflow-hidden rounded-xl border border-white/[0.07] bg-[#182126]"><div className="grid h-28 place-items-center bg-black/25">{asset.url && asset.type === 'image' ? <img src={asset.url} alt="" className="h-full w-full object-cover opacity-75" /> : <Icon className="h-8 w-8 text-[#8bd132]/70" />}</div><div className="p-4"><div className="flex items-start justify-between gap-2"><h2 className="line-clamp-2 text-[11px] font-medium text-white">{asset.title}</h2><span className="rounded bg-white/[0.05] px-1.5 py-1 text-[7px] uppercase text-[#879298]">{asset.type}</span></div><div className="mt-3 flex flex-wrap gap-1">{asset.tags.slice(0, 3).map((tag) => <span key={tag} className="rounded-full bg-[#8bd132]/[0.07] px-2 py-1 text-[7px] text-[#8bd132]">{tag}</span>)}</div>{asset.campaignId && <div className="mt-3 flex items-center gap-1.5 text-[8px] text-[#737f85]"><FolderArchive className="h-3 w-3" />Vinculado à estratégia</div>}</div></article>; })}</section></div>;
}
