import React from 'react';
import { Bot, CalendarRange, CheckCircle2, ChevronRight, Plus, Sparkles, Target } from 'lucide-react';
import { useOperations } from '../context/OperationsContext';
import type { SocialPlatform, StrategyCampaign } from '../types';

const platforms: SocialPlatform[] = ['instagram', 'linkedin', 'tiktok', 'youtube', 'facebook'];
const blank = { name: '', objective: '', startDate: '2026-08-03', endDate: '2026-08-31', budget: '', products: '', audience: '', offer: '', importantDates: '' };

export function StrategyView({ onOpenStudio }: { onOpenStudio: () => void }) {
  const { brain, campaigns, activeCampaign, setActiveCampaignId, createCampaign } = useOperations();
  const [creating, setCreating] = React.useState(false);
  const [form, setForm] = React.useState(blank);
  const [question, setQuestion] = React.useState('Qual é o resultado mais importante desta campanha?');
  const [answer, setAnswer] = React.useState('');
  const [consulting, setConsulting] = React.useState(false);
  const create = () => {
    if (!form.name.trim() || !form.objective.trim()) return;
    createCampaign({ ...form, kpis: ['Alcance qualificado', 'CTR', 'Conversões'], channels: ['instagram', 'linkedin'], funnel: 'Descoberta → Consideração → Conversão', ctas: ['Conhecer a solução', 'Solicitar demonstração'], executionPlan: ['Validar mensagem central', 'Produzir peças prioritárias', 'Agendar distribuição', 'Medir e otimizar'], status: 'planned' });
    setForm(blank); setCreating(false);
  };
  const consult = async () => {
    if (!answer.trim()) return;
    setConsulting(true);
    try {
      const response = await fetch('/api/ai/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: answer, brainContext: brain, strategyContext: activeCampaign, mode: 'strategic-consultant' }) });
      const data = await response.json();
      setQuestion(data.reply || 'Quais canais e ofertas melhor sustentam esse objetivo?');
      setAnswer('');
    } catch { setQuestion('Quais canais e ofertas melhor sustentam esse objetivo?'); setAnswer(''); }
    finally { setConsulting(false); }
  };

  return <div className="mx-auto w-full max-w-[1480px] space-y-5 p-6 2xl:p-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[0.24em] text-[#8bd132]">Planejamento orientado por IA</p><h1 className="mt-2 text-2xl font-semibold text-white">Strategy</h1><p className="mt-1 text-sm text-[#8f999f]">Toda campanha nasce aqui e carrega o contexto do Brain até o resultado.</p></div><button onClick={() => setCreating(true)} className="flex items-center gap-2 rounded-lg bg-[#8bd132] px-4 py-2.5 text-[11px] font-bold text-[#14200e]"><Plus className="h-4 w-4" />Nova campanha</button></div>
    {creating && <section className="rounded-xl border border-[#8bd132]/25 bg-[#182126] p-5"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-[#8bd132]" /><h2 className="text-sm font-semibold text-white">Estruturar nova campanha</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2">{Object.entries(form).map(([key, value]) => <label key={key} className={key === 'objective' ? 'md:col-span-2' : ''}><span className="mb-1.5 block text-[9px] uppercase tracking-[0.13em] text-[#899399]">{{ name: 'Nome', objective: 'Objetivo', startDate: 'Início', endDate: 'Fim', budget: 'Orçamento', products: 'Produtos / serviços', audience: 'Público', offer: 'Oferta', importantDates: 'Datas importantes' }[key]}</span>{key === 'objective' ? <textarea rows={3} value={value} onChange={(e) => setForm((current) => ({ ...current, [key]: e.target.value }))} className="w-full rounded-lg border border-white/[0.07] bg-black/25 p-3 text-[11px] text-white outline-none focus:border-[#8bd132]/40" /> : <input type={key.toLowerCase().includes('date') ? 'date' : 'text'} value={value} onChange={(e) => setForm((current) => ({ ...current, [key]: e.target.value }))} className="h-10 w-full rounded-lg border border-white/[0.07] bg-black/25 px-3 text-[11px] text-white outline-none focus:border-[#8bd132]/40" />}</label>)}</div><div className="mt-4 flex justify-end gap-2"><button onClick={() => setCreating(false)} className="rounded-lg px-4 py-2 text-[10px] text-[#9ca5aa]">Cancelar</button><button onClick={create} className="rounded-lg bg-[#8bd132] px-4 py-2 text-[10px] font-bold text-[#14200e]">Criar plano estratégico</button></div></section>}
    <div className="grid gap-4 xl:grid-cols-[310px_1fr_320px]">
      <section className="rounded-xl border border-white/[0.07] bg-[#182126] p-4"><h2 className="px-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-[#9ca5aa]">Campanhas</h2><div className="mt-3 space-y-2">{campaigns.map((campaign) => <button key={campaign.id} onClick={() => setActiveCampaignId(campaign.id)} className={`w-full rounded-lg border p-3 text-left ${activeCampaign?.id === campaign.id ? 'border-[#8bd132]/30 bg-[#8bd132]/[0.07]' : 'border-white/[0.05] bg-black/20'}`}><div className="flex items-start justify-between"><span className="text-[11px] font-medium text-white">{campaign.name}</span><ChevronRight className="h-4 w-4 text-[#68747a]" /></div><div className="mt-2 flex items-center justify-between text-[8px] uppercase"><span className="text-[#8bd132]">{campaign.status}</span><span className="text-[#707c82]">rev. Brain {campaign.brainRevision}</span></div></button>)}</div></section>
      <section className="rounded-xl border border-white/[0.07] bg-[#182126] p-5">{activeCampaign ? <><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[9px] uppercase tracking-[0.15em] text-[#8bd132]">Campanha ativa</span><h2 className="mt-1 text-xl font-semibold text-white">{activeCampaign.name}</h2></div><button onClick={onOpenStudio} className="rounded-lg border border-[#8bd132]/25 bg-[#8bd132]/10 px-3 py-2 text-[9px] font-semibold text-[#8bd132]">Criar no Studio</button></div><p className="mt-4 rounded-lg bg-black/20 p-4 text-[11px] leading-relaxed text-[#c7ced1]">{activeCampaign.objective}</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{[['Período', `${activeCampaign.startDate} — ${activeCampaign.endDate}`, CalendarRange], ['Orçamento', activeCampaign.budget || 'Não definido', Target], ['Público', activeCampaign.audience, Target], ['Oferta', activeCampaign.offer, Sparkles]].map(([label, value, Icon]) => <div key={String(label)} className="rounded-lg border border-white/[0.05] bg-black/15 p-3"><div className="flex items-center gap-2 text-[9px] text-[#899399]"><Icon className="h-3.5 w-3.5 text-[#8bd132]" />{String(label)}</div><p className="mt-2 text-[10px] leading-relaxed text-white">{String(value)}</p></div>)}</div><h3 className="mt-5 text-[10px] font-semibold uppercase tracking-[0.16em] text-[#9ca5aa]">Plano de execução</h3><div className="mt-3 space-y-2">{activeCampaign.executionPlan.map((step, index) => <div key={step} className="flex items-center gap-3 rounded-lg bg-black/20 p-3"><span className="grid h-5 w-5 place-items-center rounded-full bg-[#8bd132]/10 text-[8px] text-[#8bd132]">{index + 1}</span><span className="text-[10px] text-[#c8ced1]">{step}</span></div>)}</div></> : <div className="grid h-full place-items-center text-xs text-[#899399]">Selecione uma campanha.</div>}</section>
      <aside className="rounded-xl border border-white/[0.07] bg-[#182126] p-5"><div className="flex items-center gap-2"><Bot className="h-5 w-5 text-[#8bd132]" /><div><h2 className="text-[11px] font-semibold text-white">Consultor estratégico</h2><p className="text-[8px] text-[#758087]">Briefing inteligente · Brain rev. {brain.revision}</p></div></div><div className="mt-5 rounded-xl border border-[#8bd132]/15 bg-[#8bd132]/[0.055] p-4"><p className="text-[10px] leading-relaxed text-[#d6dcde]">{question}</p></div><textarea value={answer} onChange={(e) => setAnswer(e.target.value)} rows={5} placeholder="Responda com o máximo de contexto possível..." className="mt-3 w-full resize-none rounded-xl border border-white/[0.07] bg-black/25 p-3 text-[10px] text-white outline-none focus:border-[#8bd132]/35" /><button onClick={consult} disabled={consulting} className="mt-3 flex w-full items-center justify-center gap-2 rounded-lg bg-[#8bd132] py-2.5 text-[10px] font-bold text-[#14200e] disabled:opacity-60">{consulting ? <Sparkles className="h-4 w-4 animate-pulse" /> : <CheckCircle2 className="h-4 w-4" />}{consulting ? 'Analisando…' : 'Continuar briefing'}</button><div className="mt-5 text-[9px] leading-relaxed text-[#727e84]">A conversa estrutura objetivo, formatos, funil, CTAs, calendário e plano de execução antes da produção.</div></aside>
    </div>
  </div>;
}
