/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { Sidebar } from './components/Sidebar';
import { Header } from './components/Header';
import { SpotlightModal } from './components/SpotlightModal';
import { DashboardView } from './components/DashboardView';
import { AICentralView } from './components/AICentralView';
import { CreationStudioView } from './components/CreationStudioView';
import { ImageStudioView } from './components/ImageStudioView';
import { VideoEditorView } from './components/VideoEditorView';
import { EditorialCalendarView } from './components/EditorialCalendarView';
import { PublisherView } from './components/PublisherView';
import { AnalyticsView } from './components/AnalyticsView';
import { AutomationBuilderView } from './components/AutomationBuilderView';
import { CollaborationView } from './components/CollaborationView';
import { SettingsView } from './components/SettingsView';

import {
  NavigationTab,
  Workspace,
  Post,
  AIActionSuggestion,
} from './types';
import {
  INITIAL_WORKSPACES,
  INITIAL_POSTS,
  AI_SUGGESTIONS,
} from './data/mockData';

export default function App() {
  const [currentTab, setCurrentTab] = React.useState<NavigationTab>('dashboard');
  const [workspaces, setWorkspaces] = React.useState<Workspace[]>(INITIAL_WORKSPACES);
  const [activeWorkspace, setActiveWorkspace] = React.useState<Workspace>(INITIAL_WORKSPACES[0]);
  const [posts, setPosts] = React.useState<Post[]>(INITIAL_POSTS);
  const [suggestions] = React.useState<AIActionSuggestion[]>(AI_SUGGESTIONS);

  const [isSpotlightOpen, setIsSpotlightOpen] = React.useState(false);
  const [isCompact, setIsCompact] = React.useState(false);
  const [isDarkMode, setIsDarkMode] = React.useState(true);

  // Global handler to add new posts generated by AI or created manually
  const handleAddPosts = (newPostsData: Partial<Post>[]) => {
    const created: Post[] = newPostsData.map((p, idx) => ({
      id: `post-${Date.now()}-${idx}`,
      workspaceId: activeWorkspace.id,
      title: p.title || 'Conteúdo Sem Título',
      platform: p.platform || 'instagram',
      format: p.format || 'post',
      copy: p.copy || '',
      hashtags: p.hashtags || [],
      slides: p.slides,
      imageUrl: p.imageUrl,
      videoUrl: p.videoUrl,
      scheduledAt: p.scheduledAt || new Date().toISOString(),
      status: p.status || 'scheduled',
      author: p.author || 'Usuário',
      createdAt: new Date().toISOString(),
      aiScore: p.aiScore || 90,
    }));

    setPosts((prev) => [...created, ...prev]);
  };

  const handleSaveSinglePost = (postData: Partial<Post>) => {
    handleAddPosts([postData]);
    setCurrentTab('calendar');
  };

  const handleUpdateWorkspace = (updated: Workspace) => {
    setActiveWorkspace(updated);
    setWorkspaces((prev) =>
      prev.map((w) => (w.id === updated.id ? updated : w))
    );
  };

  return (
    <div
      className={`min-h-screen ${
        isDarkMode ? 'bg-[#050505] text-[#ededed]' : 'bg-slate-50 text-slate-900'
      } flex font-sans antialiased selection:bg-indigo-500 selection:text-white`}
    >
      {/* Sidebar Navigation */}
      <Sidebar
        currentTab={currentTab}
        onSelectTab={setCurrentTab}
        workspaces={workspaces}
        activeWorkspace={activeWorkspace}
        onSelectWorkspace={setActiveWorkspace}
        isCompact={isCompact}
        onOpenSpotlight={() => setIsSpotlightOpen(true)}
        onNewPost={() => setCurrentTab('creation')}
      />

      {/* Main Workspace Stage */}
      <div
        className={`flex-1 flex flex-col transition-all duration-200 ${
          isCompact ? 'pl-20' : 'pl-64'
        }`}
      >
        {/* Header Toolbar */}
        <Header
          currentTab={currentTab}
          activeWorkspace={activeWorkspace}
          onOpenSpotlight={() => setIsSpotlightOpen(true)}
          onOpenAICentral={() => setCurrentTab('ai-central')}
          onNewPost={() => setCurrentTab('creation')}
          isCompact={isCompact}
          onToggleCompact={() => setIsCompact(!isCompact)}
          isDarkMode={isDarkMode}
          onToggleDarkMode={() => setIsDarkMode(!isDarkMode)}
        />

        {/* Dynamic Tab View Area */}
        <main className="flex-1 overflow-y-auto">
          {currentTab === 'dashboard' && (
            <DashboardView
              posts={posts}
              suggestions={suggestions}
              activeWorkspace={activeWorkspace}
              onNavigate={setCurrentTab}
              onOpenCampaignWizard={() => setCurrentTab('ai-central')}
              onNewPost={() => setCurrentTab('creation')}
              onSelectPost={(p) => setCurrentTab('calendar')}
            />
          )}

          {currentTab === 'ai-central' && (
            <AICentralView
              activeWorkspace={activeWorkspace}
              onAddGeneratedPosts={(newPosts) => {
                handleAddPosts(newPosts);
                setCurrentTab('calendar');
              }}
            />
          )}

          {currentTab === 'creation' && (
            <CreationStudioView onSavePost={handleSaveSinglePost} />
          )}

          {currentTab === 'images' && <ImageStudioView />}

          {currentTab === 'video' && <VideoEditorView />}

          {currentTab === 'calendar' && (
            <EditorialCalendarView
              posts={posts}
              onSelectPost={() => {}}
              onNewPost={() => setCurrentTab('creation')}
            />
          )}

          {currentTab === 'publisher' && <PublisherView />}

          {currentTab === 'analytics' && <AnalyticsView />}

          {currentTab === 'automations' && <AutomationBuilderView />}

          {currentTab === 'collaboration' && <CollaborationView posts={posts} />}

          {currentTab === 'settings' && (
            <SettingsView
              activeWorkspace={activeWorkspace}
              onUpdateWorkspace={handleUpdateWorkspace}
              isCompact={isCompact}
              onToggleCompact={() => setIsCompact(!isCompact)}
              isDarkMode={isDarkMode}
              onToggleDarkMode={() => setIsDarkMode(!isDarkMode)}
            />
          )}
        </main>
      </div>

      {/* Spotlight Raycast Search Overlay */}
      <SpotlightModal
        isOpen={isSpotlightOpen}
        onClose={() => setIsSpotlightOpen(false)}
        onNavigate={setCurrentTab}
      />
    </div>
  );
}
