/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { Sidebar } from './components/Sidebar';
import { Header } from './components/Header';
import { SpotlightModal } from './components/SpotlightModal';
import { DashboardView } from './components/DashboardView';
import { WorkspaceView } from './components/WorkspaceView';
import { BrainView } from './components/BrainView';
import { StrategyView } from './components/StrategyView';
import { StudioView } from './components/StudioView';
import { LibraryView } from './components/LibraryView';
import { EditorialCalendarView } from './components/EditorialCalendarView';
import { PublisherView } from './components/PublisherView';
import { AnalyticsView } from './components/AnalyticsView';
import { AutomationBuilderView } from './components/AutomationBuilderView';
import { SettingsView } from './components/SettingsView';
import { ClickoLogo } from './components/ClickoLogo';
import { LoginView } from './components/LoginView';
import { TeamManagementView } from './components/TeamManagementView';
import { ApprovalsView } from './components/ApprovalsView';
import { SubscriptionView } from './components/SubscriptionView';
import { AuditLogsView } from './components/AuditLogsView';
import { AccessDeniedView } from './components/AccessDeniedView';
import { GovernanceFeedback } from './components/GovernanceFeedback';
import { useGovernance } from './context/GovernanceContext';
import { useOperations } from './context/OperationsContext';
import type { ApprovalStage } from './types';

import {
  NavigationTab,
  Post,
  AIActionSuggestion,
} from './types';
import {
  AI_SUGGESTIONS,
} from './data/mockData';

export default function App() {
  const { currentUser, canAccess, loading: governanceLoading } = useGovernance();
  const { activeWorkspace, posts, addPosts, updatePosts } = useOperations();
  const [currentTab, setCurrentTab] = React.useState<NavigationTab>('dashboard');
  const [suggestions] = React.useState<AIActionSuggestion[]>(AI_SUGGESTIONS);

  const [isSpotlightOpen, setIsSpotlightOpen] = React.useState(false);
  const [isCompact, setIsCompact] = React.useState(false);
  const [isDarkMode, setIsDarkMode] = React.useState(true);
  const [showSplash, setShowSplash] = React.useState(() => window.location.pathname !== '/login');

  React.useEffect(() => {
    if (!showSplash) return;
    const timer = window.setTimeout(() => setShowSplash(false), 780);
    return () => window.clearTimeout(timer);
  }, [showSplash]);

  // Global handler to add new posts generated by AI or created manually
  const handleAddPosts = (newPostsData: Partial<Post>[]) => {
    const created: Post[] = newPostsData.map((p, idx) => ({
      id: `post-${Date.now()}-${idx}`,
      workspaceId: activeWorkspace.id,
      title: p.title || 'Conteúdo Sem Título',
      platform: p.platform || 'instagram',
      format: p.format || 'post',
      copy: p.copy || '',
      hashtags: p.hashtags || [],
      slides: p.slides,
      imageUrl: p.imageUrl,
      videoUrl: p.videoUrl,
      scheduledAt: p.scheduledAt || new Date().toISOString(),
      status: currentUser?.role === 'collaborator' && ['scheduled', 'published'].includes(p.status || 'scheduled') ? 'pending_approval' : (p.status || 'scheduled'),
      author: p.author || currentUser?.name || 'Usuário',
      createdAt: new Date().toISOString(),
      aiScore: p.aiScore || 90,
    }));

    addPosts(created);
  };

  const handleSaveSinglePost = (postData: Partial<Post>) => {
    handleAddPosts([postData]);
    setCurrentTab('calendar');
  };

  const handleApprovalStatusChange = (contentId: string, stage: ApprovalStage) => {
    const statusMap: Record<ApprovalStage, Post['status']> = {
      draft: 'draft',
      in_review: 'in_review',
      pending_approval: 'pending_approval',
      approved: 'approved',
      changes_requested: 'changes_requested',
      rejected: 'rejected',
      published: 'published',
    };
    updatePosts((current) => current.map((post) => post.id === contentId ? { ...post, status: statusMap[stage] } : post));
  };

  const hasAccessToCurrentTab = governanceLoading || !currentUser || canAccess(currentTab);

  if (window.location.pathname.replace(/\/+$/, '') === '/login') {
    return <LoginView />;
  }

  return (
    <div data-theme={isDarkMode ? 'dark' : 'light'} className="flex min-h-screen bg-[#0B0B0B] font-sans text-[#eef1f2] antialiased selection:bg-[#B8B8B8] selection:text-[#0B0B0B]">
      {showSplash && (
        <div className="clicko-splash fixed inset-0 z-[100] grid place-items-center bg-black">
          <div className="clicko-splash-logo text-center">
            <ClickoLogo appearance="seamless" className="h-[180px] w-[360px] max-w-[78vw]" />
          </div>
        </div>
      )}
      {/* Sidebar Navigation */}
      <Sidebar
        currentTab={currentTab}
        onSelectTab={setCurrentTab}
        isCompact={isCompact}
        onToggleCompact={() => setIsCompact(!isCompact)}
        onOpenSpotlight={() => setIsSpotlightOpen(true)}
        onNewPost={() => setCurrentTab('studio')}
      />

      {/* Main Workspace Stage */}
      <div
        className={`flex min-w-0 flex-1 flex-col transition-all duration-200 ${
          isCompact ? 'pl-[76px]' : 'pl-[188px] max-[900px]:pl-[76px] 2xl:pl-[226px]'
        }`}
      >
        {/* Header Toolbar */}
        <Header
          currentTab={currentTab}
          activeWorkspace={activeWorkspace}
          onOpenSpotlight={() => setIsSpotlightOpen(true)}
          onOpenAICentral={() => setCurrentTab('strategy')}
          onNewPost={() => setCurrentTab('studio')}
          isCompact={isCompact}
          onToggleCompact={() => setIsCompact(!isCompact)}
          isDarkMode={isDarkMode}
          onToggleDarkMode={() => setIsDarkMode(!isDarkMode)}
        />

        {/* Dynamic Tab View Area */}
        <main className="flex-1 overflow-x-hidden overflow-y-auto">
          {!hasAccessToCurrentTab && <AccessDeniedView onBack={() => setCurrentTab('dashboard')} />}

          {hasAccessToCurrentTab && currentTab === 'dashboard' && (
            <DashboardView
              posts={posts}
              suggestions={suggestions}
              activeWorkspace={activeWorkspace}
              onNavigate={setCurrentTab}
              onOpenCampaignWizard={() => setCurrentTab('strategy')}
              onNewPost={() => setCurrentTab('studio')}
              onSelectPost={(p) => setCurrentTab('calendar')}
            />
          )}

          {hasAccessToCurrentTab && currentTab === 'workspace' && <WorkspaceView onNavigate={setCurrentTab} />}

          {hasAccessToCurrentTab && currentTab === 'brain' && <BrainView />}

          {hasAccessToCurrentTab && currentTab === 'strategy' && <StrategyView onOpenStudio={() => setCurrentTab('studio')} />}

          {hasAccessToCurrentTab && currentTab === 'studio' && <StudioView onSavePost={handleSaveSinglePost} />}

          {hasAccessToCurrentTab && currentTab === 'library' && <LibraryView />}

          {hasAccessToCurrentTab && currentTab === 'calendar' && (
            <EditorialCalendarView
              posts={posts}
              onSelectPost={() => {}}
              onNewPost={() => setCurrentTab('studio')}
            />
          )}

          {hasAccessToCurrentTab && currentTab === 'publisher' && <PublisherView />}

          {hasAccessToCurrentTab && currentTab === 'analytics' && <AnalyticsView />}

          {hasAccessToCurrentTab && currentTab === 'automations' && <AutomationBuilderView />}

          {hasAccessToCurrentTab && currentTab === 'approvals' && <ApprovalsView onStatusChange={handleApprovalStatusChange} />}

          {hasAccessToCurrentTab && currentTab === 'team' && <TeamManagementView />}

          {hasAccessToCurrentTab && currentTab === 'subscription' && <SubscriptionView />}

          {hasAccessToCurrentTab && currentTab === 'audit-logs' && <AuditLogsView />}

          {hasAccessToCurrentTab && currentTab === 'settings' && <SettingsView />}
        </main>
      </div>

      {/* Spotlight Raycast Search Overlay */}
      <SpotlightModal
        isOpen={isSpotlightOpen}
        onClose={() => setIsSpotlightOpen(false)}
        onNavigate={setCurrentTab}
      />
      <GovernanceFeedback />
    </div>
  );
}
