/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from "react";
import { SpotlightModal } from "./components/SpotlightModal";
import { DashboardView } from "./components/DashboardLabView";
import { WorkspaceView } from "./components/WorkspaceView";
import { BrainView } from "./components/BrainView";
import { StrategyView } from "./components/StrategyView";
import { StudioView } from "./components/StudioImmersiveView";
import { LibraryView } from "./components/LibraryView";
import { ImageStudioView } from "./components/ImageStudioView";
import { VideoEditorView } from "./components/VideoEditorView";
import { CreationStudioView } from "./components/CreationStudioView";
import { AIChatView } from "./components/AIChatView";
import { FloatingAIAssistant } from "./components/FloatingAIAssistant";
import { TemplatesView } from "./components/TemplatesView";
import { ConnectedAccountsView } from "./components/ConnectedAccountsView";
import { EditorialCalendarView } from "./components/EditorialCalendarView";
import { PublisherView } from "./components/PublisherView";
import { AnalyticsView } from "./components/AnalyticsView";
import { AutomationBuilderView } from "./components/AutomationBuilderView";
import { SettingsView } from "./components/SettingsView";
import { ClickoLogo } from "./components/ClickoLogo";
import { LoginView } from "./components/LoginView";
import { TeamManagementView } from "./components/TeamManagementView";
import { ApprovalsView } from "./components/ApprovalsView";
import { SubscriptionView } from "./components/SubscriptionView";
import { AuditLogsView } from "./components/AuditLogsView";
import { AccessDeniedView } from "./components/AccessDeniedView";
import { GovernanceFeedback } from "./components/GovernanceFeedback";
import { useGovernance } from "./context/GovernanceContext";
import { useOperations } from "./context/OperationsContext";
import type { ApprovalStage } from "./types";
import { useTabRouter } from "./app/router/navigation";
import { LabGlobalSurfaces } from "./product/LabGlobalSurfaces";
import {
  isProductSurfacePath,
  ProductSurfaceView,
} from "./product/ProductSurfaceView";
import { screenForLocation } from "./product/screenManifest";
import { CanonicalProduct, isCanonicalPath } from "./canonical/CanonicalProduct";

import { NavigationTab, Post, AIActionSuggestion } from "./types";
import { AI_SUGGESTIONS } from "./data/mockData";

export default function App() {
  const {
    currentUser,
    canAccess,
    loading: governanceLoading,
  } = useGovernance();
  const { activeWorkspace, posts, addPosts, updatePosts } = useOperations();
  const {
    currentTab,
    pathname,
    search,
    navigate: setCurrentTab,
    navigatePath,
  } = useTabRouter("dashboard");
  const [suggestions] = React.useState<AIActionSuggestion[]>(AI_SUGGESTIONS);

  const [isSpotlightOpen, setIsSpotlightOpen] = React.useState(false);
  const [showSplash, setShowSplash] = React.useState(
    () => window.location.pathname !== "/login",
  );

  React.useEffect(() => {
    if (!showSplash) return;
    const timer = window.setTimeout(() => setShowSplash(false), 780);
    return () => window.clearTimeout(timer);
  }, [showSplash]);

  // Global handler to add new posts generated by AI or created manually
  const handleAddPosts = (newPostsData: Partial<Post>[]) => {
    const created: Post[] = newPostsData.map((p, idx) => ({
      id: `post-${Date.now()}-${idx}`,
      workspaceId: activeWorkspace.id,
      title: p.title || "Conteúdo Sem Título",
      platform: p.platform || "instagram",
      format: p.format || "post",
      copy: p.copy || "",
      hashtags: p.hashtags || [],
      slides: p.slides,
      imageUrl: p.imageUrl,
      videoUrl: p.videoUrl,
      scheduledAt: p.scheduledAt || new Date().toISOString(),
      status:
        currentUser?.role === "collaborator" &&
        ["scheduled", "published"].includes(p.status || "scheduled")
          ? "pending_approval"
          : p.status || "scheduled",
      author: p.author || currentUser?.name || "Usuário",
      createdAt: new Date().toISOString(),
      aiScore: p.aiScore || 90,
      clientId: p.clientId,
      campaignId: p.campaignId,
      strategyId: p.strategyId,
      brainRevision: p.brainRevision,
      objective: p.objective,
      origin: p.origin,
      creativeIdeaId: p.creativeIdeaId,
      clickScoreBreakdown: p.clickScoreBreakdown,
    }));

    addPosts(created);
  };

  const handleSaveSinglePost = (postData: Partial<Post>) => {
    handleAddPosts([postData]);
    setCurrentTab("calendar");
  };

  const handleApprovalStatusChange = (
    contentId: string,
    stage: ApprovalStage,
  ) => {
    const statusMap: Record<ApprovalStage, Post["status"]> = {
      draft: "draft",
      in_review: "in_review",
      pending_approval: "pending_approval",
      approved: "approved",
      changes_requested: "changes_requested",
      rejected: "rejected",
      published: "published",
    };
    updatePosts((current) =>
      current.map((post) =>
        post.id === contentId ? { ...post, status: statusMap[stage] } : post,
      ),
    );
  };

  const hasAccessToCurrentTab =
    governanceLoading || !currentUser || canAccess(currentTab);
  const productSurface = isProductSurfacePath(pathname);
  const focusMode = pathname.startsWith("/content/") && pathname.includes("/edit");
  const stitchScreen = screenForLocation(pathname, search);

  if (window.location.pathname.replace(/\/+$/, "") === "/login") {
    return <LoginView />;
  }

  if (isCanonicalPath(pathname)) {
    return (
      <CanonicalProduct
        pathname={pathname}
        search={search}
        onNavigate={navigatePath}
      />
    );
  }

  return (
    <div
      data-theme="dark"
      data-stitch-screen={stitchScreen?.id}
      data-stitch-state={stitchScreen?.state}
      className="clicko-unified-shell clicko-lab-shell min-h-screen bg-[#101010] font-sans text-[#f4eeee] antialiased selection:bg-[#ff6969] selection:text-[#190b0b]"
    >
      {showSplash && (
        <div className="clicko-splash fixed inset-0 z-[100] grid place-items-center bg-black">
          <div className="clicko-splash-logo text-center">
            <ClickoLogo
              appearance="seamless"
              className="h-[180px] w-[360px] max-w-[78vw]"
            />
          </div>
        </div>
      )}
      <LabGlobalSurfaces
        pathname={pathname}
        search={search}
        onNavigate={navigatePath}
        onOpenSpotlight={() => setIsSpotlightOpen(true)}
      />

      <div className="pl-[76px]">
        <main className={`clicko-main-stage min-h-screen overflow-x-hidden ${focusMode ? "clicko-main-stage--focus" : "clicko-main-stage--shell"}`}>
          {!hasAccessToCurrentTab && (
            <AccessDeniedView onBack={() => setCurrentTab("dashboard")} />
          )}

          {hasAccessToCurrentTab && productSurface && (
            <ProductSurfaceView
              pathname={pathname}
              search={search}
              onNavigate={navigatePath}
            />
          )}

          {hasAccessToCurrentTab && !productSurface && (
            <>
              {hasAccessToCurrentTab && currentTab === "dashboard" && (
                <DashboardView
                  posts={posts}
                  suggestions={suggestions}
                  activeWorkspace={activeWorkspace}
                  onNavigate={setCurrentTab}
                  onOpenCampaignWizard={() => setCurrentTab("ai-chat")}
                  onNewPost={() => setCurrentTab("create-copy")}
                  onSelectPost={(p) => setCurrentTab("calendar")}
                />
              )}

              {hasAccessToCurrentTab && currentTab === "workspace" && (
                <WorkspaceView onNavigate={setCurrentTab} />
              )}

              {hasAccessToCurrentTab && currentTab === "brain" && <BrainView />}

              {hasAccessToCurrentTab && currentTab === "strategy" && (
                <StrategyView onOpenStudio={() => setCurrentTab("studio")} />
              )}

              {hasAccessToCurrentTab && currentTab === "studio" && (
                <StudioView onSavePost={handleSaveSinglePost} />
              )}

              {hasAccessToCurrentTab && currentTab === "library" && (
                <LibraryView onOpenStudio={() => setCurrentTab("studio")} />
              )}

              {hasAccessToCurrentTab && currentTab === "create-image" && (
                <ImageStudioView />
              )}

              {hasAccessToCurrentTab && currentTab === "create-video" && (
                <VideoEditorView />
              )}

              {hasAccessToCurrentTab && currentTab === "create-copy" && (
                <CreationStudioView onSavePost={handleSaveSinglePost} />
              )}

              {hasAccessToCurrentTab && currentTab === "ai-chat" && (
                <AIChatView onNavigate={setCurrentTab} />
              )}

              {hasAccessToCurrentTab && currentTab === "templates" && (
                <TemplatesView />
              )}

              {hasAccessToCurrentTab && currentTab === "connected-accounts" && (
                <ConnectedAccountsView />
              )}

              {hasAccessToCurrentTab && currentTab === "calendar" && (
                <EditorialCalendarView
                  posts={posts}
                  onSelectPost={() => {}}
                  onNewPost={() => setCurrentTab("create-copy")}
                />
              )}

              {hasAccessToCurrentTab && currentTab === "publisher" && (
                <PublisherView />
              )}

              {hasAccessToCurrentTab && currentTab === "analytics" && (
                <AnalyticsView onOpenStudio={() => setCurrentTab("studio")} />
              )}

              {hasAccessToCurrentTab && currentTab === "automations" && (
                <AutomationBuilderView />
              )}

              {hasAccessToCurrentTab && currentTab === "approvals" && (
                <ApprovalsView onStatusChange={handleApprovalStatusChange} />
              )}

              {hasAccessToCurrentTab && currentTab === "team" && (
                <TeamManagementView />
              )}

              {hasAccessToCurrentTab && currentTab === "subscription" && (
                <SubscriptionView />
              )}

              {hasAccessToCurrentTab && currentTab === "audit-logs" && (
                <AuditLogsView />
              )}

              {hasAccessToCurrentTab && currentTab === "settings" && (
                <SettingsView />
              )}
            </>
          )}
        </main>
      </div>

      {/* Spotlight Raycast Search Overlay */}
      <SpotlightModal
        isOpen={isSpotlightOpen}
        onClose={() => setIsSpotlightOpen(false)}
        onNavigate={setCurrentTab}
      />
      <GovernanceFeedback />
      {!focusMode && (
        <FloatingAIAssistant
          currentTab={currentTab}
          onOpenFullChat={() => setCurrentTab("ai-chat")}
        />
      )}
    </div>
  );
}
